/// Dealer dimension table with geographic and tier information
table dim_dealer

	column dealer_id
		dataType: string
		isKey
		sourceColumn: dealer_id
		summarizeBy: none

	column dealer_name
		dataType: string
		sourceColumn: dealer_name
		summarizeBy: none

	column country
		dataType: string
		dataCategory: Country
		sourceColumn: country
		summarizeBy: none

	column region
		dataType: string
		sourceColumn: region
		summarizeBy: none

	column city
		dataType: string
		sourceColumn: city
		summarizeBy: none

	column dealer_tier
		dataType: string
		sourceColumn: dealer_tier
		summarizeBy: none

	partition dim_dealer = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents("G:/Data/projekty/PowerBI_demo/data/dim_dealer.csv"), [Delimiter=",", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				ChangedTypes = Table.TransformColumnTypes(PromotedHeaders,{{"dealer_id", type text}, {"dealer_name", type text}, {"country", type text}, {"region", type text}, {"city", type text}, {"dealer_tier", type text}})
			in
				ChangedTypes
