{
  "compatibilityLevel": 1567,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "dim_date",
        "description": "Date dimension table for time-based analysis",
        "columns": [
          {
            "name": "date",
            "dataType": "dateTime",
            "formatString": "yyyy-MM-dd",
            "isKey": true,
            "sourceColumn": "date",
            "summarizeBy": "none"
          },
          {
            "name": "year",
            "dataType": "int64",
            "sourceColumn": "year",
            "summarizeBy": "none"
          },
          {
            "name": "quarter",
            "dataType": "string",
            "sourceColumn": "quarter",
            "summarizeBy": "none"
          },
          {
            "name": "month",
            "dataType": "int64",
            "sourceColumn": "month",
            "summarizeBy": "none"
          },
          {
            "name": "month_name",
            "dataType": "string",
            "sortByColumn": "month",
            "sourceColumn": "month_name",
            "summarizeBy": "none"
          },
          {
            "name": "year_month",
            "dataType": "string",
            "sourceColumn": "year_month",
            "summarizeBy": "none"
          },
          {
            "name": "day_of_week",
            "dataType": "string",
            "sourceColumn": "day_of_week",
            "summarizeBy": "none"
          },
          {
            "name": "is_weekend",
            "dataType": "boolean",
            "sourceColumn": "is_weekend",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "dim_date",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"G:/Data/projekty/PowerBI_demo/data/dim_date.csv\"), [Delimiter=\",\", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {{\"date\", type date}, {\"year\", Int64.Type}, {\"quarter\", type text}, {\"month\", Int64.Type}, {\"month_name\", type text}, {\"year_month\", type text}, {\"day_of_week\", type text}, {\"is_weekend\", type logical}})",
                "in",
                "    ChangedTypes"
              ]
            }
          }
        ]
      },
      {
        "name": "dim_dealer",
        "description": "Dealer dimension table with geographic and tier information",
        "columns": [
          {
            "name": "dealer_id",
            "dataType": "string",
            "isKey": true,
            "sourceColumn": "dealer_id",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_name",
            "dataType": "string",
            "sourceColumn": "dealer_name",
            "summarizeBy": "none"
          },
          {
            "name": "country",
            "dataType": "string",
            "sourceColumn": "country",
            "summarizeBy": "none"
          },
          {
            "name": "region",
            "dataType": "string",
            "sourceColumn": "region",
            "summarizeBy": "none"
          },
          {
            "name": "city",
            "dataType": "string",
            "sourceColumn": "city",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_tier",
            "dataType": "string",
            "sourceColumn": "dealer_tier",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "dim_dealer",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"G:/Data/projekty/PowerBI_demo/data/dim_dealer.csv\"), [Delimiter=\",\", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {{\"dealer_id\", type text}, {\"dealer_name\", type text}, {\"country\", type text}, {\"region\", type text}, {\"city\", type text}, {\"dealer_tier\", type text}})",
                "in",
                "    ChangedTypes"
              ]
            }
          }
        ]
      },
      {
        "name": "dim_model",
        "description": "Vehicle model dimension table",
        "columns": [
          {
            "name": "model_id",
            "dataType": "string",
            "isKey": true,
            "sourceColumn": "model_id",
            "summarizeBy": "none"
          },
          {
            "name": "model_name",
            "dataType": "string",
            "sourceColumn": "model_name",
            "summarizeBy": "none"
          },
          {
            "name": "segment",
            "dataType": "string",
            "sourceColumn": "segment",
            "summarizeBy": "none"
          },
          {
            "name": "fuel_type",
            "dataType": "string",
            "sourceColumn": "fuel_type",
            "summarizeBy": "none"
          },
          {
            "name": "vehicle_class",
            "dataType": "string",
            "sourceColumn": "vehicle_class",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "dim_model",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"G:/Data/projekty/PowerBI_demo/data/dim_model.csv\"), [Delimiter=\",\", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {{\"model_id\", type text}, {\"model_name\", type text}, {\"segment\", type text}, {\"fuel_type\", type text}, {\"vehicle_class\", type text}})",
                "in",
                "    ChangedTypes"
              ]
            }
          }
        ]
      },
      {
        "name": "fact_sales",
        "description": "Sales fact table — wholesale transactions from SuperAuto to dealers",
        "columns": [
          {
            "name": "sales_id",
            "dataType": "string",
            "isKey": true,
            "sourceColumn": "sales_id",
            "summarizeBy": "none"
          },
          {
            "name": "date",
            "dataType": "dateTime",
            "formatString": "yyyy-MM-dd",
            "sourceColumn": "date",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_id",
            "dataType": "string",
            "sourceColumn": "dealer_id",
            "summarizeBy": "none"
          },
          {
            "name": "model_id",
            "dataType": "string",
            "sourceColumn": "model_id",
            "summarizeBy": "none"
          },
          {
            "name": "units_sold",
            "dataType": "int64",
            "sourceColumn": "units_sold",
            "summarizeBy": "sum"
          },
          {
            "name": "unit_price",
            "dataType": "double",
            "formatString": "€ #,##0.00",
            "sourceColumn": "unit_price",
            "summarizeBy": "none"
          },
          {
            "name": "gross_revenue",
            "dataType": "double",
            "formatString": "€ #,##0.00",
            "sourceColumn": "gross_revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "discount_pct",
            "dataType": "double",
            "formatString": "0.00%",
            "sourceColumn": "discount_pct",
            "summarizeBy": "none"
          },
          {
            "name": "discount_amount",
            "dataType": "double",
            "formatString": "€ #,##0.00",
            "sourceColumn": "discount_amount",
            "summarizeBy": "sum"
          },
          {
            "name": "net_revenue",
            "dataType": "double",
            "formatString": "€ #,##0.00",
            "sourceColumn": "net_revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "unit_cost",
            "dataType": "double",
            "formatString": "€ #,##0.00",
            "sourceColumn": "unit_cost",
            "summarizeBy": "none"
          },
          {
            "name": "total_cost",
            "dataType": "double",
            "formatString": "€ #,##0.00",
            "sourceColumn": "total_cost",
            "summarizeBy": "sum"
          },
          {
            "name": "profit",
            "dataType": "double",
            "formatString": "€ #,##0.00",
            "sourceColumn": "profit",
            "summarizeBy": "sum"
          },
          {
            "name": "margin_pct",
            "dataType": "double",
            "formatString": "0.00%",
            "sourceColumn": "margin_pct",
            "summarizeBy": "none"
          }
        ],
        "measures": [
          {
            "name": "Net Revenue",
            "description": "Total net revenue across all sales",
            "expression": "SUM(fact_sales[net_revenue])",
            "formatString": "€ #,##0"
          },
          {
            "name": "Units Sold",
            "description": "Total units sold",
            "expression": "SUM(fact_sales[units_sold])",
            "formatString": "#,##0"
          },
          {
            "name": "Total Profit",
            "description": "Total profit",
            "expression": "SUM(fact_sales[profit])",
            "formatString": "€ #,##0"
          },
          {
            "name": "Margin %",
            "description": "Profit margin percentage",
            "expression": "DIVIDE([Total Profit], [Net Revenue], 0)",
            "formatString": "0.0%"
          },
          {
            "name": "Avg Selling Price",
            "description": "Average selling price per unit",
            "expression": "DIVIDE([Net Revenue], [Units Sold], 0)",
            "formatString": "€ #,##0"
          },
          {
            "name": "Avg Discount %",
            "description": "Average discount percentage",
            "expression": "AVERAGE(fact_sales[discount_pct])",
            "formatString": "0.0%"
          },
          {
            "name": "Gross Revenue",
            "description": "Total gross revenue before discounts",
            "expression": "SUM(fact_sales[gross_revenue])",
            "formatString": "€ #,##0"
          },
          {
            "name": "Total Cost",
            "description": "Total cost",
            "expression": "SUM(fact_sales[total_cost])",
            "formatString": "€ #,##0"
          },
          {
            "name": "Cost per Unit",
            "description": "Cost per unit",
            "expression": "DIVIDE([Total Cost], [Units Sold], 0)",
            "formatString": "€ #,##0"
          },
          {
            "name": "Revenue YoY %",
            "description": "Year-over-year revenue growth",
            "expression": [
              "VAR CurrentRevenue = [Net Revenue]",
              "VAR PreviousRevenue = CALCULATE([Net Revenue], SAMEPERIODLASTYEAR(dim_date[date]))",
              "RETURN",
              "    DIVIDE(CurrentRevenue - PreviousRevenue, PreviousRevenue, BLANK())"
            ],
            "formatString": "0.0%"
          },
          {
            "name": "Transaction Count",
            "description": "Number of transactions",
            "expression": "COUNTROWS(fact_sales)",
            "formatString": "#,##0"
          },
          {
            "name": "Selected Metric",
            "description": "Metric switched by Field Parameter slicer",
            "expression": [
              "SWITCH(",
              "    SELECTEDVALUE('Metric Parameter'[Metric Parameter Order]),",
              "    0, [Net Revenue],",
              "    1, [Total Profit],",
              "    2, [Margin %],",
              "    3, [Units Sold]",
              ")"
            ]
          },
          {
            "name": "Selected Metric Formatted",
            "description": "Formatted value of selected metric",
            "expression": [
              "VAR _sel = SELECTEDVALUE('Metric Parameter'[Metric Parameter Order])",
              "RETURN",
              "    SWITCH(",
              "        _sel,",
              "        0, FORMAT([Net Revenue], \"€ #,##0\"),",
              "        1, FORMAT([Total Profit], \"€ #,##0\"),",
              "        2, FORMAT([Margin %], \"0.0%\"),",
              "        3, FORMAT([Units Sold], \"#,##0\")",
              "    )"
            ]
          },
          {
            "name": "Adjusted Discount %",
            "description": "Adjusted discount after what-if parameter",
            "expression": "[Avg Discount %] + [Discount Change Value]",
            "formatString": "0.0%"
          },
          {
            "name": "Simulated Profit",
            "description": "Profit after discount change simulation",
            "expression": [
              "VAR DiscountShift = [Discount Change Value]",
              "VAR OriginalGross = [Gross Revenue]",
              "VAR NewDiscount = [Avg Discount %] + DiscountShift",
              "VAR NewNetRevenue = OriginalGross * (1 - NewDiscount)",
              "VAR Cost = [Total Cost]",
              "RETURN",
              "    NewNetRevenue - Cost"
            ],
            "formatString": "€ #,##0"
          },
          {
            "name": "Profit Impact",
            "description": "Difference between simulated and actual profit",
            "expression": "[Simulated Profit] - [Total Profit]",
            "formatString": "€ #,##0"
          },
          {
            "name": "Dynamic Title Overview",
            "description": "Dynamic page title for Executive Overview",
            "expression": [
              "VAR _region = IF(",
              "    ISFILTERED(dim_dealer[region]),",
              "    SELECTEDVALUE(dim_dealer[region], \"Multiple Regions\"),",
              "    \"All Regions\"",
              ")",
              "VAR _year = IF(",
              "    ISFILTERED(dim_date[year]),",
              "    FORMAT(SELECTEDVALUE(dim_date[year]), \"0\"),",
              "    \"2024-2025\"",
              ")",
              "RETURN",
              "    \"Sales Performance \u2014 \" & _region & \", \" & _year"
            ]
          },
          {
            "name": "Dynamic Title Product",
            "description": "Dynamic page title for Product & Dealer Analysis",
            "expression": [
              "VAR _model = IF(",
              "    ISFILTERED(dim_model[model_name]),",
              "    SELECTEDVALUE(dim_model[model_name], \"Multiple Models\"),",
              "    \"All Models\"",
              ")",
              "VAR _year = IF(",
              "    ISFILTERED(dim_date[year]),",
              "    FORMAT(SELECTEDVALUE(dim_date[year]), \"0\"),",
              "    \"2024-2025\"",
              ")",
              "RETURN",
              "    \"Product & Dealer Analysis \u2014 \" & _model & \", \" & _year"
            ]
          },
          {
            "name": "Dealer Revenue Rank",
            "description": "Dealer ranking by revenue",
            "expression": [
              "IF(",
              "    HASONEVALUE(dim_dealer[dealer_name]),",
              "    RANKX(",
              "        ALL(dim_dealer[dealer_name]),",
              "        [Net Revenue],",
              "        ,",
              "        DESC,",
              "        Dense",
              "    )",
              ")"
            ],
            "formatString": "#,##0"
          },
          {
            "name": "Dealer Margin Rank",
            "description": "Dealer ranking by margin",
            "expression": [
              "IF(",
              "    HASONEVALUE(dim_dealer[dealer_name]),",
              "    RANKX(",
              "        ALL(dim_dealer[dealer_name]),",
              "        [Margin %],",
              "        ,",
              "        DESC,",
              "        Dense",
              "    )",
              ")"
            ],
            "formatString": "#,##0"
          },
          {
            "name": "PY Revenue",
            "description": "Revenue in previous year",
            "expression": "CALCULATE([Net Revenue], SAMEPERIODLASTYEAR(dim_date[date]))",
            "formatString": "€ #,##0"
          },
          {
            "name": "PY Profit",
            "description": "Profit in previous year",
            "expression": "CALCULATE([Total Profit], SAMEPERIODLASTYEAR(dim_date[date]))",
            "formatString": "€ #,##0"
          },
          {
            "name": "Profit YoY %",
            "description": "Year-over-year profit growth",
            "expression": [
              "VAR Current = [Total Profit]",
              "VAR Previous = [PY Profit]",
              "RETURN",
              "    DIVIDE(Current - Previous, Previous, BLANK())"
            ],
            "formatString": "0.0%"
          }
        ],
        "partitions": [
          {
            "name": "fact_sales",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"G:/Data/projekty/PowerBI_demo/data/fact_sales.csv\"), [Delimiter=\",\", Columns=14, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {{\"sales_id\", type text}, {\"date\", type date}, {\"dealer_id\", type text}, {\"model_id\", type text}, {\"units_sold\", Int64.Type}, {\"unit_price\", type number}, {\"gross_revenue\", type number}, {\"discount_pct\", type number}, {\"discount_amount\", type number}, {\"net_revenue\", type number}, {\"unit_cost\", type number}, {\"total_cost\", type number}, {\"profit\", type number}, {\"margin_pct\", type number}})",
                "in",
                "    ChangedTypes"
              ]
            }
          }
        ]
      },
      {
        "name": "Metric Parameter",
        "description": "Field Parameter for switching between key metrics",
        "columns": [
          {
            "name": "Metric Parameter",
            "dataType": "string",
            "isDefaultLabel": true,
            "sourceColumn": "Metric Parameter",
            "sortByColumn": "Metric Parameter Order",
            "summarizeBy": "none"
          },
          {
            "name": "Metric Parameter Order",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Metric Parameter Order",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Metric Parameter",
            "dataView": "full",
            "source": {
              "type": "calculated",
              "expression": [
                "DATATABLE(",
                "    \"Metric Parameter\", STRING,",
                "    \"Metric Parameter Order\", INTEGER,",
                "    {",
                "        {\"Net Revenue\", 0},",
                "        {\"Profit\", 1},",
                "        {\"Margin %\", 2},",
                "        {\"Units Sold\", 3}",
                "    }",
                ")"
              ]
            }
          }
        ]
      },
      {
        "name": "Discount Change",
        "description": "What-If parameter for discount change simulation (-10% to +10%)",
        "columns": [
          {
            "name": "Discount Change",
            "dataType": "double",
            "isDefaultLabel": true,
            "formatString": "0.0%",
            "sourceColumn": "[Value]",
            "summarizeBy": "none"
          }
        ],
        "measures": [
          {
            "name": "Discount Change Value",
            "description": "Selected discount change from what-if slicer",
            "expression": "SELECTEDVALUE('Discount Change'[Discount Change], 0)",
            "formatString": "0.0%"
          }
        ],
        "partitions": [
          {
            "name": "Discount Change",
            "dataView": "full",
            "source": {
              "type": "calculated",
              "expression": "GENERATESERIES(-0.10, 0.10, 0.01)"
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "fact_to_date",
        "fromColumn": "date",
        "fromTable": "fact_sales",
        "toColumn": "date",
        "toTable": "dim_date"
      },
      {
        "name": "fact_to_dealer",
        "fromColumn": "dealer_id",
        "fromTable": "fact_sales",
        "toColumn": "dealer_id",
        "toTable": "dim_dealer"
      },
      {
        "name": "fact_to_model",
        "fromColumn": "model_id",
        "fromTable": "fact_sales",
        "toColumn": "model_id",
        "toTable": "dim_model"
      }
    ]
  }
}
